name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip Xcode project
        run: unzip "Cash App.xcodeproj.zip"

      - name: Set Default Scheme
        run: |
          scheme="CashappSpoof"
          echo $scheme > default
          echo Using scheme: $scheme

      - name: Build
        env:
          scheme: ${{ 'CashappSpoof' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild build-for-testing -scheme "$scheme" -project "Cash App.xcodeproj" -destination "platform=$platform,name=$device"

      - name: Check for tests and run if available
        env:
          scheme: ${{ 'CashappSpoof' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          if xcodebuild -scheme "$scheme" -project "Cash App.xcodeproj" -list | grep -q "Test"; then
            echo "Tests found. Running tests..."
            xcodebuild test-without-building -scheme "$scheme" -project "Cash App.xcodeproj" -destination "platform=$platform,name=$device"
          else
            echo "No tests found in the scheme. Skipping test step."
          fi
